allauth/urls.py
from importlib import import_module

from django.urls import include, path

from allauth.socialaccount import providers

from . import app_settings


urlpatterns = [path('', include('allauth.account.urls'))]

if app_settings.SOCIALACCOUNT_ENABLED:
    urlpatterns += [path('social/', include('allauth.socialaccount.urls'))]

# Provider urlpatterns, as separate attribute (for reusability).
provider_urlpatterns = []
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue
    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)
    if prov_urlpatterns:
        provider_urlpatterns += prov_urlpatterns
urlpatterns += provider_urlpatterns

classroom/urls.py
from django.urls import include, path

from .views.classroom import *
from .views import students, teachers


urlpatterns = [
    path('', home, name='home'),
    path('about', about, name='about'),
    path('courses', courses, name='courses'),
    path('course_details', course_details, name='course_details'),
    path('notyet', notyet, name='notyet'),
    path('faqs',faqs, name='faqs'),
    path('gradient_students', gradient_students, name='gradient_students'),

    path('students/', include(([
        path('', students.dashboard, name='quiz_list'),
        path('dashboard', students.dashboard, name='app-student-dashboard'),
        path('directory_grid', students.directory_grid, name='app-directory-grid'),
        path('take_course', students.take_course, name='app-take-course'),
        path('edit_user', students.edit_user, name='edit_user'),
        path('mentors', students.mentor_list, name='mentors'),
        path('what_is_ml', students.what_is_ml, name='what_is_machine_learning'),
        path('end_to_end', students.end_to_end, name='building_end_to_end'),
        path('linear_reg', students.linear_reg, name='linear_regression'),
        path('logistic_reg', students.logistic_reg, name='logistic_regression'),
        path('log_reg', students.logistic_reg_example, name='log_reg'),
        path('knearest', students.knearest, name='knearest'),
        path('k_nearest_practical', students.k_nearest_practical, name='k_nearest_practical'),
        path('decision_tree', students.decision_tree, name='decision_tree'),
        path('decision_tree_from_scratch', students.decision_tree_from_scratch, name='decision_tree_from_scratch'),
        path('descriptive_stats', students.descriptive, name='descriptive_stats'),
        path('descriptive_two', students.descript_stats, name='descriptive_two'),
        path('probability_one', students.proba_one, name='probability_one'),
        path('probability_one_exercises', students.proba_one_exercises, name='probability_one_exercises'),
        path('probability_exercises_two', students.proba_two_exercises, name='probability_exercises_two'),
        path('monty_hall', students.monty_hall, name='monty_hall'),
        path('probability_two', students.proba_two, name='probability_two'),
        path('probability_exercises_three', students.proba_three_exercises, name='probability_exercises_three'),
        path('bayesian_theory', students.bayesian_theory, name='bayesian_theory'),
        path('bayesian_exercises', students.bayesian_exercises, name='bayesian_exercises'),
        path('central_limit_theorem', students.central_limit_theorem, name='central_limit_theorem'),
        path('inferential_statistics', students.inferential_stats, name='inferential_statistics'),
        path('what_is_python_expressions.html', students.python_expressions, name='what_is_python_expressions.html'),
        path('control_flow_and_conditionals', students.control_flow_and_conditionals, name='control_flow_and_conditionals'),
        path('opening_and_reading', students.opening_and_reading, name='opening_and_reading'),
        path('pandas_one', students.pandas_one, name='pandas_one'),
        path('pandas_two', students.pandas_two, name='pandas_two'),
        path('object_oriented_programming', students.object_oriented_programming, name='object_oriented_programming'),
        path('data_visualization_notes', students.data_visualization_notes, name='data_visualization_notes'),
        path('messages', students.messages, name='messages'),
        ], 'classroom'), namespace='students')),

    path('teachers/', include(([
        path('', teachers.mentor_dashboard, name='app-instructor-dashboard'),
        path('edit_user', teachers.edit_user, name='edit_user'),
        path('mentor_messages', teachers.mentor_messages, name='mentor_messages'),
        path('statement', teachers.statement, name='app-instructor-statement'),
        path('course_details', teachers.course_details, name='app-take-course'),
        path('students', teachers.student_list, name='students'),
        path('take_course', teachers.take_course, name='app-take-course'),
        path('payment_view', teachers.payment_view, name='payment_view'),
        ], 'classroom'), namespace='teachers')),
]

classroom/views/classroom.py
from django.shortcuts import redirect, render

#redirects after signup
def home(request):
    if request.user.is_authenticated and request.user.is_allow:
        if request.user.is_teacher:
            return redirect('teachers:app-instructor-dashboard')
        elif request.user.is_student:
            return redirect('students:app-student-dashboard')
    return render(request, 'classroom/home.html')

#about us page
def about(request):
    return render(request, 'classroom/about-us.html')
#courses page
def courses(request):
    return render(request, 'classroom/courses.html')
#course details
def course_details(request):
    return render(request, 'classroom/course-details.html')
#not yet
def notyet(request):
    return render(request, 'classroom/notyet.html')
#faqs
def faqs(request):
    return render(request, 'classroom/faqs.html')

def gradient_students(request):
    return render(request, 'classroom/gradient-students.html')

classroom/views/students.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView
from ..decorators import student_required, check_is_allow
from ..forms import *
from ..models import Quiz, Student, TakenQuiz, Mentor
from django.http import HttpResponseRedirect
import json

from django.contrib.auth import get_user_model
User = get_user_model()


# class StudentSignUpView(CreateView):
    # model = User
    # form_class = StudentSignUpForm
    # template_name = 'registration/signup_form.html'

    # def get_context_data(self, **kwargs):
    #     kwargs['user_type'] = 'student'
    #     return super().get_context_data(**kwargs)

    # def form_valid(self, form):
    #     user = form.save()
    #     login(self.request, user)
    #     return redirect('students:app-student-dashboard')

#logging out
# @method_decorator([login_required, student_required], name='dispatch')
# @login_required
# @student_required
# def logout_request(request):
#     logout(request)
#     messages.info(request, "You have successfully been logged out")
#     return redirect('student:app-student-dashboard')


@login_required
@student_required
@check_is_allow
def dashboard(request):
    # if request.user.is_allow:
    return render(request, 'classroom/students/app-student-dashboard.html')
    # else:
        # messages.warning(request, 'You account is not approved from admin yet')
        # return redirect('home')

#directory grid
# @method_decorator([login_required, student_required], name='dispatch')
@login_required
@student_required
@check_is_allow
def directory_grid(request):
    return render(request, 'classroom/students/app-directory-grid.html')

#course page
# @method_decorator([login_required, student_required], name='dispatch')
@login_required
@student_required
@check_is_allow
def take_course(request):
    return render(request, 'classroom/students/app-take-course.html')

#conditionally redirect based on cohort, emails is a list from the first cohort
@login_required
@student_required
@check_is_allow
def messages(request):
    emails = ['bewarangritmwa@gmail.com', 'pgshandino@gmail.com', 'jibolaofficial@gmail.com',
              'derenibenny@gmail.com', 'davidakin6@gmail.com']
    if request.user.email in emails:
        return redirect('https://app.slack.com/client/TSH0SAYLQ/CSK753T62')
    else:
        return redirect('https://app.slack.com/client/TSH0SAYLQ/G015XB30ML5')

#https://app.slack.com/client/TSH0SAYLQ/CSK753T62
#edit student profile page
@login_required
@student_required
@check_is_allow
def edit_user(request):
    user = request.user
    if request.method == 'POST':
        form = StudentUserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('%s' % (reverse('students:edit_user')))
    else:
        form = StudentUserForm(instance=user)
    return render(request, 'classroom/students/app-student-profile.html', {'form': form})

#get list of mentors
@login_required
@student_required
@check_is_allow
def mentor_list(request):
    mentors = User.objects.filter(is_teacher=True).select_related('mentor')
    for user in mentors:
        try:
            print(user.mentor.linkedin)
        except:
            pass
    # for user in mentors:
    #     print(user.linkedin)
    template_name = 'classroom/students/mentor_list.html'
    context = {'mentors': mentors}
    return render(request, template_name, context)

#course material
@login_required
@check_is_allow
def what_is_ml(request):
    return render(request, 'classroom/students/what_is_machine_learning.html')

@login_required
@check_is_allow
def end_to_end(request):
    return render(request, 'classroom/students/building_end_to_end.html')

@login_required
@check_is_allow
def linear_reg(request):
    return render(request, 'classroom/students/Linear_Regression.html')

@login_required
@check_is_allow
def logistic_reg(request):
    return render(request, 'classroom/students/logistic_regression.html')

@login_required
@check_is_allow
def logistic_reg_example(request):
    return render(request, 'classroom/students/log_reg.html')

@login_required
@check_is_allow
def knearest(request):
    return render(request, 'classroom/students/knearest.html')

@login_required
@check_is_allow
def k_nearest_practical(request):
    return render(request, 'classroom/students/knearestneighbors.html')

@login_required
@check_is_allow
def decision_tree(request):
    return render(request, 'classroom/students/decisiontree.html')

@login_required
@check_is_allow
def decision_tree_from_scratch(request):
    return render(request, 'classroom/students/decision_tree_from_scratch.html')

@login_required
@check_is_allow
def descriptive(request):
    return render(request, 'classroom/students/descriptive_statistics.html')

@login_required
@check_is_allow
def descript_stats(request):
    return render(request, 'classroom/students/descr_stats_graphs.html')

@login_required
@check_is_allow
def proba_one(request):
    return render(request, 'classroom/students/probability_one.html')

@login_required
@check_is_allow
def proba_one_exercises(request):
    return render(request, 'classroom/students/probability_one_exercises.html')

@login_required
@check_is_allow
def proba_two_exercises(request):
    return render(request, 'classroom/students/probability_exercises_two.html')

@login_required
@check_is_allow
def proba_two(request):
    return render(request, 'classroom/students/probability_two.html')

@login_required
@check_is_allow
def monty_hall(request):
    return render(request, 'classroom/students/monty_hall.html')

@login_required
@check_is_allow
def proba_three_exercises(request):
    return render(request, 'classroom/students/probability_exercises_three.html')

@login_required
@check_is_allow
def bayesian_theory(request):
    return render(request, 'classroom/students/bayesian_theory.html')

@login_required
@check_is_allow
def bayesian_exercises(request):
    return render(request, 'classroom/students/bayesian_exercises.html')

@login_required
@check_is_allow
def central_limit_theorem(request):
    return render(request, 'classroom/students/central_limit_theorem.html')

@login_required
@check_is_allow
def inferential_stats(request):
    return render(request, 'classroom/students/inferential_statistics.html')

@login_required
@check_is_allow
def python_expressions(request):
    return render(request, 'classroom/students/what_is_python_expressions.html')

@login_required
@check_is_allow
def control_flow_and_conditionals(request):
    return render(request, 'classroom/students/control_flow_and_conditionals.html')

@login_required
@check_is_allow
def opening_and_reading(request):
    return render(request, 'classroom/students/opening_and_reading.html')

@login_required
@check_is_allow
def pandas_one(request):
    return render(request, 'classroom/students/pandas_one.html')

@login_required
@check_is_allow
def pandas_two(request):
    return render(request, 'classroom/students/pandas_two.html')

@check_is_allow
@login_required
def object_oriented_programming(request):
    return render(request, 'classroom/students/object_oriented_programming.html')

@check_is_allow
@login_required
def data_visualization_notes(request):
    return render(request, 'classroom/students/dataviz.html')


@method_decorator([login_required, student_required, check_is_allow], name='dispatch')
class TakenQuizListView(ListView):
    model = TakenQuiz
    context_object_name = 'taken_quizzes'
    template_name = 'classroom/students/taken_quiz_list.html'

    def get_queryset(self):
        queryset = self.request.user.student.taken_quizzes \
            .select_related('quiz', 'quiz__subject') \
            .order_by('quiz__name')
        return queryset


@login_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Quiz, pk=pk)
    student = request.user.student

    if student.quizzes.filter(pk=pk).exists():
        return render(request, 'students/taken_quiz.html')

    total_questions = quiz.questions.count()
    unanswered_questions = student.get_unanswered_questions(quiz)
    total_unanswered_questions = unanswered_questions.count()
    progress = 100 - round(((total_unanswered_questions - 1) / total_questions) * 100)
    question = unanswered_questions.first()

    if request.method == 'POST':
        form = TakeQuizForm(question=question, data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                student_answer = form.save(commit=False)
                student_answer.student = student
                student_answer.save()
                if student.get_unanswered_questions(quiz).exists():
                    return redirect('students:take_quiz', pk)
                else:
                    correct_answers = student.quiz_answers.filter(answer__question__quiz=quiz, answer__is_correct=True).count()
                    score = round((correct_answers / total_questions) * 100.0, 2)
                    TakenQuiz.objects.create(student=student, quiz=quiz, score=score)
                    if score < 50.0:
                        messages.warning(request, f'Better luck next time! Your score for the quiz %s was {(quiz.name, score)}')
                    else:
                        messages.success(request, 'Congratulations! You completed the quiz %s with success! You scored {(quiz.name, score)} points.')
                    return redirect('students:quiz_list')
    else:
        form = TakeQuizForm(question=question)

    return render(request, 'classroom/students/take_quiz_form.html', {
        'quiz': quiz,
        'question': question,
        'form': form,

classroom/templates/classroom/teachers/app-instructor-profile.html
{% load static %}
<!DOCTYPE html>
<html class="st-layout ls-top-navbar-large ls-bottom-footer show-sidebar sidebar-l3" lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>The Gradient Boost</title>

  <link href="{% static 'second/css/vendor/all.css' %}" rel="stylesheet">
  <link href="{% static 'second/css/app/app.css' %}" rel="stylesheet">
  <link rel="icon" href="{% static 'second/images/learningmaterial/favicon.ico' %}">


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!-- If you don't need support for Internet Explorer <= 8 you can safely remove these -->
  <!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

</head>

<body>

  <!-- Wrapper required for sidebar transitions -->
  <div class="st-container">

    <!-- Fixed navbar -->
    <div class="navbar navbar-size-large navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="#sidebar-menu" data-toggle="sidebar-menu" class="toggle pull-left visible-xs"><i class="fa fa-ellipsis-v"></i></a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand navbar-brand-primary navbar-brand-logo navbar-nav-padding-left">
            <a class="svg" href="{% url 'teachers:app-instructor-dashboard' %}">
              <svg viewBox="0 0 106 64" height="100%" width="100%" preserveAspectRatio="xMidYMid meet">
                <img src="{% static 'second/images/learning-logo.PNG' %}" width="80%" height="76%">
              </svg>
            </a>
          </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="main-nav">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Courses <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="https://emmanuelgradientboost.typeform.com/to/ghVivR">Suggest Course Changes</a></li>
                <li><a href="{% url 'teachers:app-take-course' %}">Courses Details</a></li>
              </ul>
            </li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Instructor <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="active"><a href="{% url 'teachers:app-instructor-dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'teachers:payment_view'%}">Edit Billing</a></li>
                <li><a href="https://app.slack.com/client/TSH0SAYLQ/CSK753T62">Messages</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-nav-bordered navbar-right">
            <!-- User -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle user" data-toggle="dropdown">
                {{ user.first_name }} <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'teachers:payment_view'%}">Billing</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->

      </div>
    </div>

    <!-- Sidebar component with st-effect-1 (set on the toggle button within the navbar) -->
    <div class="sidebar left sidebar-size-3 sidebar-offset-0 sidebar-visible-desktop sidebar-visible-mobile sidebar-skin-dark" id="sidebar-menu" data-type="collapse">
      <div data-scrollable>

        <div class="sidebar-block">
          <div class="profile">
            <h4 class="text-display-1 margin-none">{{ user.first_name }}</h4>
          </div>
        </div>

        <ul class="sidebar-menu">
          <li><a href="{% url 'teachers:app-instructor-dashboard' %}"><i class="fa fa-home"></i><span>Dashboard</span></a></li>
          <li><a href="https://app.slack.com/client/TSH0SAYLQ/CSK753T62"><i class="fa fa-paper-plane"></i><span>Messages</span></a></li>
<!--          <li><a href="{% url 'teachers:students' %}"><i class="fa fa-users"></i><span>List of Students</span></a></li>-->
<!--{#          <li><a href="{% url 'teachers:app-instructor-statement' %}"><i class="fa fa-dollar"></i><span>Statement</span></a></li>#}-->
          <li><a href="{% url 'logout' %}">Logout</a></li>
        </ul>
      </div>
    </div>

    <!-- sidebar effects OUTSIDE of st-pusher: -->
    <!-- st-effect-1, st-effect-2, st-effect-4, st-effect-5, st-effect-9, st-effect-10, st-effect-11, st-effect-12, st-effect-13 -->
{#                <li><a href="{% url 'teachers:payment_view'%}">Edit Billing</a></li>#}

    <!-- content push wrapper -->
    <div class="st-pusher" id="content">

      <!-- sidebar effects INSIDE of st-pusher: -->
      <!-- st-effect-3, st-effect-6, st-effect-7, st-effect-8, st-effect-14 -->

      <!-- this is the wrapper for the content -->
      <div class="st-content">

        <!-- extra div for emulating position:fixed of the menu -->
        <div class="st-content-inner padding-none">

          <div class="container-fluid">

            <div class="page-section third">
              <!-- Tabbable Widget -->
              <div class="tabbable paper-shadow relative" data-z="0.5">

                <!-- Tabs -->
                <ul class="nav nav-tabs">
                    <li><a href="{% url 'teachers:edit_user' %}"><i class="fa fa-fw fa-lock"></i> <span class="hidden-sm hidden-xs">Manage Account</span></a></li>
                    <li><a href="{% url 'teachers:payment_view'%}"><i class="fa fa-fw fa-credit-card"></i> <span class="hidden-sm hidden-xs">Billing Details</span></a></li>
                </ul>
                <!-- // END Tabs -->

                <!-- Panes -->
                <div class="tab-content">

                  <div id="account" class="tab-pane active">
                    <form id="edit-mentor-profile" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
<!--{#                      <div class="form-group">#}-->
<!--{#                        <label for="photo" class="col-sm-2 control-label">Avatar</label>#}-->
<!--{#                        <div class="col-md-6">#}-->
<!--{#                          <div class="media v-middle">#}-->
<!--{#                            <div class="media-left">#}-->
<!--{#                              <div class="icon-block width-100 bg-grey-100">#}-->
<!--{#                                  <img id="image" style="width:99%;height:99%;">#}-->
<!--{#                                <i class="fa fa-photo text-light"></i>#}-->
<!--{#                              </div>#}-->
<!--{#                            </div>#}-->
<!--{#                            <div class="media-body">#}-->
<!--{#                                <input type="file" id="files"  name="photo" class="btn btn-white btn-sm paper-shadow relative" data-z="0.5" data-hover-z="1" data-animated/>#}-->
<!--{#                              <a href="#" class="btn btn-white btn-sm paper-shadow relative" data-z="0.5" data-hover-z="1" data-animated> Add Image<i class="fa fa-upl"></i></a>#}-->
<!--{#                            </div>#}-->
<!--{#                          </div>#}-->
<!--{#                        </div>#}-->
<!--{#                      </div>#}-->
                      <div class="form-group">
                        <label for="inputEmail3" class="col-md-2 control-label">Full Name</label>
                        <div class="col-md-8">
                          <div class="row">
                            <div class="col-md-6">
                              <div class="form-control-material">
                                {{ form.first_name }}
                                <label for="edit-mentor-profile-first_name"></label>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="form-control-material">
                                {{ form.last_name }}
                                <label for="edit-mentor-profile-last_name"></label>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="email" class="col-md-2 control-label">Email</label>
                        <div class="col-md-6">
                          <div class="form-control-material">
                            <div class="input-group">
                              <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                              {{ form.email }}
                              <label for="edit-mentor-profile-email"></label>
                            </div>
                          </div>
                        </div>
                      </div>
<!--{#                      <div class="form-group">#}-->
<!--{#                        <label for="inputEmail3" class="col-md-2 control-label">LinkedIn</label>#}-->
<!--{#                        <div class="col-md-6">#}-->
<!--{#                          <div class="form-control-material">#}-->
<!--{#                            <div class="input-group">#}-->
<!--{#                              <span class="input-group-addon"><i class="fa fa-link"></i></span>#}-->
<!--{#                              <input type="text" class="form-control used" id="website" value="www.mosaicpro.biz">#}-->
<!--{#                              <label for="website">LinkedIn</label>#}-->
<!--{#                            </div>#}-->
<!--{#                          </div>#}-->
<!--{#                        </div>#}-->
<!--{#                      </div>#}-->
<!--{#                      <div class="form-group">#}-->
<!--{#                        <label for="inputPassword3" class="col-md-2 control-label">Change Password</label>#}-->
<!--{#                        <div class="col-md-6">#}-->
<!--{#                          <div class="form-control-material">#}-->
<!--{#                            <input type="password" class="form-control" id="password" placeholder="Password">#}-->
<!--{#                            <label for="inputPassword3">Password</label>#}-->
<!--{#                          </div>#}-->
<!--{#                        </div>#}-->
<!--{#                      </div>#}-->
                      <div class="form-group">
                        <div class="col-md-offset-2 col-md-6">
                          <div class="checkbox checkbox-success">
                            <input id="checkbox3" type="checkbox" checked="">
                            <label for="checkbox3">Subscribe to our Newsletter</label>
                          </div>
                        </div>
                      </div>
                      <div class="form-group margin-none">
                        <div class="col-md-offset-2 col-md-10">
                          <button type="submit" class="btn btn-primary paper-shadow relative" data-z="0.5" data-hover-z="1" data-animated>Save Changes</button>
                        </div>
                      </div>
                    </form>
                  </div>

                </div>
                <!-- // END Panes -->

              </div>
              <!-- // END Tabbable Widget -->

            </div>

          </div>

        </div>
        <!-- /st-content-inner -->

      </div>
      <!-- /st-content -->

    </div>
    <!-- /st-pusher -->

    <!-- Footer -->
    <footer class="footer">
        <strong>Built by <a href="http://hooros.co.za/">Hooros Digital</strong> </a> GradientBoost &copy; Copyright 2020
    </footer>
    <!-- // Footer -->

  </div>
  <!-- /st-container -->

  <!-- Inline Script for colors and config objects; used by various external scripts; -->
  <script>
    var colors = {
      "danger-color": "#e74c3c",
      "success-color": "#81b53e",
      "warning-color": "#f0ad4e",
      "inverse-color": "#2c3e50",
      "info-color": "#2d7cb5",
      "default-color": "#6e7882",
      "default-light-color": "#cfd9db",
      "purple-color": "#9D8AC7",
      "mustard-color": "#d4d171",
      "lightred-color": "#e15258",
      "body-bg": "#f6f6f6"
    };
    var config = {
      theme: "html",
      skins: {
        "default": {
          "primary-color": "#42a5f5"
        }
      }
    };
  </script>

  <script src="{% static 'second/js/vendor/all.js' %}"></script>
  <script src="{% static 'second/js/app/app.js' %}"></script>

  <script>document.getElementById("files").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
  };
  </script>


</body>

</html>

classroom/templates/classroom/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">Add first the text of the question. In the next step you will be able to add the possible answers.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary" role="button">Nevermind</a>
  </form>
{% endblock %}

classroom/templates/classroom/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}